### ISSUE TITLE
Bug in a quantize! function?

### ISSUE THREAD

**Issue by indra-uolles** [rogercampos/png_quantizator#4]
I wrote the following code (we use gem Piet, which calls functions from your gem):

```
class PartnerImageUploader < CarrierWave::Uploader::Base
  include Sprockets::Rails::Helper
  include CarrierWave::MiniMagick
  include Piet::CarrierWaveExtension
  include CarrierWave::S3CacheUrl
  include CarrierWave::IdinaidiDefaults

  fog_public true

  version :full do
    process resize_to_fit: [180, 50]
    process :pngquant
  end

end
```
it worked, but I also saw that in the app folder files with names like this: ```"#<File/0x007fe654ceb750>"``` appeared and they didn't get cleared. I extracted the code from your gem to a ruby script, and added this line of code:
```
Image.new("star_number_1.png").quantize!
```
when I executed it, I saw that it created a file with the name like this - ```"#<File/0x007fe654ceb750>"``` and screwed up the original file. So I concluded that quantize! function didn't work correctly.

I changed the code like this:

```
def quantize!(colors = 256)
  temp_path = "#{SecureRandom.hex(16)}.png"
  temp_file = Tempfile.new(temp_path)
  res = quantize_to(temp_path, colors)
  FileUtils.cp(temp_path, @file_path)
  temp_file.close
  FileUtils.rm temp_path
  res
end
``` 
and it worked correctly. What do you think about that?

P.S. Here's what I also found: http://hiltmon.com/blog/2013/01/11/ruby-tempfile-aggressive-unlink/

**Comment by rogercampos** [comment]
I just fixed it and released a new minor release. Thanks for the bug report!
